# Generated by Django 5.2.3 on 2025-11-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='chefs/')),
                ('verified', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=4.0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('price', models.CharField(max_length=50)),
                ('is_elite', models.BooleanField(default=False)),
            ],
        ),
    ]
