# Generated by Django 5.2.3 on 2025-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefapp', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
